### ISSUE TITLE
minecraft@2.1.15376: hash check failed

### ISSUE THREAD

**Issue by RaphaelTarita** [Calinou/scoop-games#130] opened 2020-06-17 21:29 UTC
```
Installing 'minecraft' (2.1.15376) [64bit]
Minecraft.exe (2,8 MB) [==========================================================================================================================================================] 100%
Checking hash of Minecraft.exe ... ERROR Hash check failed!
App:         games/minecraft
URL:         https://launcher.mojang.com/download/Minecraft.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d9cdcf6fae6bd3ddc5c8a61b4453a75f5516b71e518ee3e410fa8df591940e70
Actual:      e6b10c53f5f7c501747e4ffb87a43a7a6cb60201866863531d96b4114aa2fb21

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=minecraft%402.1.15376%3a+hash+check+failed
```

**Comment by Calinou** [comment] 2020-06-18 07:38
Duplicate of #128.

**Closed by Calinou** 2020-06-18 07:38 UTC
