### ISSUE TITLE
gzdoom@4.11.3: download via aria2 failed, github-actions bot mistakenly thinks the files can be downloaded just fine

### ISSUE THREAD

**Issue by hylianux** [Calinou/scoop-games#1051] opened 2023-10-30 22:07 UTC
```shell
PS C:\Users\[Redacted]> scoop update gzdoom
gzdoom: 4.11.2 -> 4.11.3
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Updating one outdated app:
Updating 'gzdoom' (4.11.2 -> 4.11.3)
Downloading new version
Starting download with aria2 ...
Download: 10/30 17:56:52 [ERROR] CUID#8 - Download aborted. URI=https://github.com/coelckers/gzdoom/releases/download/g4.11.3/gzDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/ZDoom/gzdoom/releases/download/g4.11.3/gzdoom-4Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 2b7527|ERR |       0B/s|C:/Users/[Redacted]/scoop/cache/gzdoom#4.11.3#https_github.com_coelckers_gzdoom_releases_download_g4.11.3_gzdoom-4-11-3-Windows-64bit.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/coelckers/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3-Windows-64bit.zip
    referer=https://github.com/coelckers/gzdoom/releases/download/g4.11.3/
    dir=C:\Users\[Redacted]\scoop\cache
    out=gzdoom#4.11.3#https_github.com_coelckers_gzdoom_releases_download_g4.11.3_gzdoom-4-11-3-Windows-64bit.zip

ERROR & 'C:\Users\[Redacted]\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\[Redacted]\scoop\cache\gzdoom.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=51832 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=gzdoom%404.11.3%3a+download+via+aria2+failed
```

In short, the problem is this link `https://github.com/coelckers/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3-Windows-64bit.zip` is a link that goes to a Not Found error screen... the link that needs to be in there is [this one](https://github.com/ZDoom/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3.a.-Windows-64bit.zip): `https://github.com/ZDoom/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3.a.-Windows-64bit.zip`

**Comment by hylianux** [comment] 2023-10-30 22:19
Well let's go through the list: 
- not a network error, I'm able to download all sorts of things from github, just not this one.
- I'm in the USA... my ISP doesn't block anything, and even if it did, I tried vpn's just to verify it
- I don't use an antivirus other than the basic one that comes with windows (defender)
- I don't use a proxy
- it's not an aria2 problem because I can reproduce the issue by simply putting that link in my browser and getting the same error.

The release page you're trying to grab the latest gzdoom from is from a user named "[coelckers](https://github.com/coelckers?tab=repositories)".  One glance at the list of his repositories they're maintaining, and you will not find gzdoom among them.  This link is doomed to fail.  You need to use the official repository, not this user's fork of the repository.

Like I said - you need to use [https://github.com/ZDoom/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3.a.-Windows-64bit.zip}(https://github.com/ZDoom/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3.a.-Windows-64bit.zip) (note that the filename is also different on this link).  This is the official download link.

**Comment by YagiGreg** [comment] 2023-11-07 06:33
The problem isn't strictly the user's namespace; I believe it was at coelckers/gzdoom before being moved to zdoom/gzdoom, and github redirects old repo urls. Indeed, the url https://github.com/coelckers/gzdoom/releases/download/g4.11.3/gzdoom-4-11-3.a.-Windows-64bit.zip with the coelckers namespace downloads successfully.

The real problem is the incorrect filename, `gzdoom-4-11-3.a.-Windows-64bit.zip` with a stray `.a.` bit in there (which doesn't seem to mean anything, from what I can tell, and was mistakenly placed there by the uploader).

I suspect the bot thinks this link works because it returns an HTTP 301 response, and does not follow it to determine whether the actual url is accessible.

**Comment by Calinou** [comment] 2023-11-07 10:09
Is there a way to temporarily disable the bot on a specific manifest? This would allow fixing the manifest until a new GZDoom version is uploaded without a nonstandard version scheme.

**Comment by hylianux** [comment] 2023-11-19 01:59
... I saw a comment pop up in my email a while ago with a link to the github-actions log demonstrating that the github-actions bot failed to download the file but still continued anyway as if it had, but it doesn't appear here in this ticket... Was it removed?  If not, I can resend the link to the log spot again here.  Just let me know.

**Comment by Calinou** [comment] 2023-11-19 13:53
> ... I saw a comment pop up in my email a while ago with a link to the github-actions log demonstrating that the github-actions bot failed to download the file but still continued anyway as if it hadn't, but it doesn't appear here in this ticket... Was it removed? If not, I can resend the link to the log spot again here. Just let me know.

I don't see any removed comments here. That said, GitHub only displays a public log if someone removes someone else's comment, but not if someone removes their own comment.

**Comment by hylianux** [comment] 2023-11-21 15:32
Mkay, then the missing comment that I saw had this to say (if the original poster removed it, I'm not sure for what reason, but if it's somehow helpful, then great).

> The execution log for this run shows that the bot did indeed fail to download the file, but then it ignored the error and closed the ticket regardless. [https://github.com/Calinou/scoop-games/actions/runs/6699266249/job/18203086583#step:3:366](https://github.com/Calinou/scoop-games/actions/runs/6699266249/job/18203086583#step:3:366)

**Comment by mmelvin0** [comment] 2023-11-23 02:50
My PR doesn't close this issue, as it doesn't address the bot failure above, just fixes the manifest to reflect the new ZDoom Github org.

**Closed** 2023-11-23 13:48 UTC
Labels: bug
