### ISSUE TITLE
xonotic@0.8.5: decompress error

### ISSUE THREAD

**Issue by Vintic** [Calinou/scoop-games#978] opened 2023-05-30 14:47 UTC
Don't have admin rights, but other apps are installed normally, except xonotic, Error from file ~\scoop\apps\xonotic\0.8.5\7zip.log:

```
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 1228561792 bytes (1172 MiB)

Extracting archive: C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\xonotic-0.8.5.zip
--
Path = C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\xonotic-0.8.5.zip
Type = zip
Physical Size = 1228561792


Sub items Errors: 15

Archives with Errors: 1

Sub items Errors: 15
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\Frameworks\SDL2.framework\SDL2
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\Frameworks\SDL2.framework\Headers
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\Frameworks\SDL2.framework\Versions\Current
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\Frameworks\SDL2.framework\Resources
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libvorbis.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libode.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libtheora.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libvorbisfile.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libogg.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libfreetype.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libd0_rijndael.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libd0_blind_id.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\Xonotic.app\Contents\MacOS\libvorbisenc.dylib
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\xonotic-linux-dedicated.sh
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\vvv.aaa\scoop\apps\xonotic\0.8.5\Xonotic\xonotic-linux-glx.sh

```

**Comment by Calinou** [comment] 2023-05-31 09:16
Is there a way we can get rid of specific files *before* having Scoop move files around? We could remove macOS/Linux-specific files before installation.

**Comment by SonaliBendre** [comment] 2023-06-03 13:10
```
PS C:\> scoop install xonotic
WARN  Purging previous failed installation of xonotic.
ERROR 'xonotic' isn't installed correctly.
Removing older version (0.8.5).
'xonotic' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'xonotic' (0.8.5) [64bit] from games bucket
Loading xonotic-0.8.5.zip from cache.
Checking hash of xonotic-0.8.5.zip ... ok.
Extracting xonotic-0.8.5.zip ... Could not find 'Xonotic'! (error 11)
At D:\scoop\apps\scoop\current\lib\core.ps1:638 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'Xonotic'! (error 11):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'Xonotic'! (error 11)
```

**Comment by Calinou** [comment] 2023-08-20 18:23
Duplicate of https://github.com/Calinou/scoop-games/issues/818.

**Closed by Calinou** 2023-08-20 18:23 UTC
Labels: bug
