### ISSUE TITLE
mgba-dev400.8.2-6239 a hash check failed

### ISSUE THREAD

**Issue by bearachute** [Calinou/scoop-games#131] opened 2020-06-30 08:17 UTC
Installing 'mgba-dev' (0.8.2-6239) [64bit]
mGBA-build-latest-win64.7z (10.8 MB) [==============================================] 100%
Checking hash of mGBA-build-latest-win64.7z ... ERROR Hash check failed!
App:         games/mgba-dev
URL:         https://s3.amazonaws.com/mgba/mGBA-build-latest-win64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    a53cb4bf225fd39009e4c007f7a092582eecafdfa10746cd4692db7325965aec
Actual:      11df0563380c7823150fdec02d0728ab8585deb91bb5dd10551ab6c3807e2ccc

happens on reinstall and also when it's installed and you try and update it, 

windows 10 up to date, fresh install of scoop

**Comment by issaclin32** [comment] 2020-08-11 06:39
This problem is automatically fixed by a package update. (`0.8.2-6239` -> `0.8.3`)

**Comment by issaclin32** [comment] 2020-08-11 07:04
This problem is caused by that the file is already updated by the developer of **mGBA** (for example, `0.8.2-6239` -> `0.8.2-6245`). Since the download URL remains the same (`https://s3.amazonaws.com/mgba/mGBA-build-latest-win64.7z`), hash check is always going to fail before *Scoop* automatically updates the manifest (for every 3 hours).

To solve the problem, you can either:
1. Wait for a few hours and install `mgba-dev` again.
2. Update the manifest by running `powershell -File "(SCOOP DIRECTORY)\buckets\games\bin\checkver.ps1" -f mgba-dev`.

**Comment by Calinou** [comment] 2021-02-14 17:32
I can't reproduce this here; `mgba-dev` installs correctly. This was probably fixed a while ago, closing.

**Closed by Calinou** 2021-02-14 17:32 UTC
Labels: bug
