### ISSUE TITLE
(request) add unciv

### ISSUE THREAD

**Issue by metalfoxdev** [Calinou/scoop-games#682] opened 2022-08-20 14:38 UTC
Unciv is an open source reimplementation of Civ V
https://github.com/yairm210/Unciv

**Comment by metalfoxdev** [comment] 2022-08-21 08:43
i am working on this issue

**Comment by Calinou** [comment] 2022-12-31 16:40
Duplicate of https://github.com/Calinou/scoop-games/issues/484.

**Closed by Calinou** 2022-12-31 16:40 UTC
Labels: new package
