### ISSUE TITLE
ioquake3@nightly: download via aria2 failed

### ISSUE THREAD

**Issue by satorope** [Calinou/scoop-games#340] opened 2021-10-16 11:37 UTC
ERROR Download failed! (Error 3) Resource was not found
ERROR https://ioquake3.org/files/jenkins/latest/gcc/no_options/release-mingw32-x86_64.zip
    referer=https://ioquake3.org/files/jenkins/latest/gcc/no_options/
    dir=C:\Users\user\scoop\cache
    out=ioquake3#nightly-20211016#https_ioquake3.org_files_jenkins_latest_gcc_no_options_release-mingw32-x86_64.zip

ERROR & 'C:\Users\user\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\user\scoop\cache\ioquake3.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=1504 --continue --summary-interval 0
iortcw

**Comment by Calinou** [comment] 2021-10-16 13:32
I can't update ioquake3 currently because the new download is a ZIP archive *within* a ZIP archive. There's no way to handle this in Scoop (not without a post-install script at least).

If you know how to write this script, feel free to open a pull request :slightly_smiling_face:

**Comment by Calinou** [comment] 2022-02-28 14:27
Duplicate of #303.

**Closed by Calinou** 2022-02-28 14:27 UTC
Labels: bug
