### ISSUE TITLE
[Bug]: Unable to install multimc, its hash always changed.

### ISSUE THREAD

**Issue by indrakaw** [Calinou/scoop-games#860] opened 2023-03-31 18:02 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

multimc

### Expected/Current Behaviour

Get it installed and working normally.

Due to the downloaded file hash doesn't match to manifest, it can't be installed. I have no idea why, this is the 3+ times I made reports about it. I'm not trolling.

### Steps to Reproduce

```console
PS> scoop install multimc
WARN  Purging previous failed installation of multimc.
ERROR 'multimc' isn't installed correctly.
Removing older version (0.6.14).
'multimc' was uninstalled.
Installing 'multimc' (0.6.14) [64bit] from games bucket
Downloading https://files.multimc.org/downloads/mmc-stable-win32.zip (-1 B)...

Checking hash of mmc-stable-win32.zip ... ERROR Hash check failed!
App:         games/multimc
URL:         https://files.multimc.org/downloads/mmc-stable-win32.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    f6e7a8c0a8a7b27139f7e6cf7c7f5a97300ac2d8f864df0820d16d9fdadae12d
Actual:      3e5cb5559d2ab2a578963121a08a6a0a3fbb9e5aff0025a8dd100ccd4949022f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=multimc%400.6.14%3a+hash+check+failed
```

### Possible Solution

Look up the source and do something, maybe? I have no idea what to do at the moment.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
41183f8c1 (HEAD -> master, origin/master, origin/HEAD) vscodium: Update to version 1.77.0.23090

'games' bucket:
6e73ecf5 (HEAD -> master, origin/master, origin/HEAD) multimc@0.6.14: Fix hash (Closes #858)

'main' bucket:
51a980933 (HEAD -> master, origin/master, origin/HEAD) syft: Update to version 0.76.0
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-04-01T00:57:56.1858309+07:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by RuiNtD** [comment] 2023-03-31 18:32
Duplicate of #822. Just use `prismlauncher` instead.

**Comment by indrakaw** [comment] 2023-03-31 19:41
I'm not familiar with `prismlauncher`. I guess it will do. 

Feel free to close this issues or leave it be to let other knows.

**Closed** 2023-03-31 20:33 UTC
Labels: bug
